server {
  listen 80;
  server_name funchat.changee.cloud;

  # 분산 로그 포맷 적용 `/var/log/nginx/access.log`에서 볼 수 있음
  log_format upstream_log '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          '"$http_referer" "$http_user_agent" '
                          'rt=$request_time urt=$upstream_response_time '
                          'uaddr=$upstream_addr ustat=$upstream_status';
  access_log /var/log/nginx/access.log upstream_log;

  # 배포 시 Jenkins가 아래 파일을 blue/green 중 하나로 교체한 뒤 nginx -s reload 합니다.
  include /etc/nginx/conf.d/upstream.conf;

  # API는 백엔드로 로드밸런싱
  location /api/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 3s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    proxy_pass http://funchat_app_upstream;
  }

  location / {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout 3s;
    proxy_send_timeout 30s;
    proxy_read_timeout 30s;

    proxy_pass http://funchat_web_upstream;
  }
}
