upstream funchat_web_upstream {
  # green stack web (DNS alias -> multiple A records 가능)
  server funchat_green_web:80 resolve;
  keepalive 32;
}

upstream funchat_app_upstream {
  # green stack app (DNS alias -> app scale 시 라운드로빈)
  server funchat_green_app:8081 resolve;
  keepalive 32;
}
