upstream funchat_web_upstream {
  zone funchat_web_upstream 64k;
  # blue stack web (DNS alias -> multiple A records 가능)
  server funchat_blue_web:80 resolve;
  keepalive 32;
}

upstream funchat_app_upstream {
  zone funchat_app_upstream 64k;
  # blue stack app (DNS alias -> app scale 시 라운드로빈)
  server funchat_blue_app:8081 resolve;
  keepalive 32;
}
