upstream funchat_web_upstream {
  zone funchat_web_upstream 64k;
  include /etc/nginx/conf.d/upstream.web.servers.conf;
  keepalive 32;
}

upstream funchat_app_upstream {
  zone funchat_app_upstream 64k;
  include /etc/nginx/conf.d/upstream.app.servers.conf;
  keepalive 32;
}
