spring:
  datasource:
    url: jdbc:mysql://localhost:3306/funchat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${USER_ID}
    password: ${USER_PW}
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    database-platform:
      org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mongodb:
    host: localhost
    port: 27017
    database: funchat
    username: ${USER_ID}
    password: ${USER_PW}
    authentication-database: admin  # 사용자 인증은 admin DB에 저장된 계정 기준으로 수행

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${ACCESS_EXPIRATION}
  refresh-expiration: ${REFRESH_EXPIRATION}